### ISSUE TITLE
Update for GNOME 3.18

### ISSUE THREAD

**Issue by kparal** [manno/gnome-shell-extension-quicklaunch#13]
Hello,

GNOME 3.18 has been released and many people already use it. Could you please update your extension at extensions.gnome.org to support this new GNOME version?

Thanks!

**Comment by manno** [comment]
Hi,
Sorry, I'm no longer using gnome-shell. I've fallen for a tiling window manager some time ago. Sadly none of my Linux desktops has packages for 3.18, so I can't trivially test it.

**Comment by kparal** [comment]
I see, thanks for info. Maybe you could adjust `README` and call for a new maintainer, if you don't intend to maintain this in the future (not sure I understood you correctly)? Let's see if someone pops up.

As for GNOME 3.18, you can easily test it with Fedora 23 Beta [1], but I understand it's not as trivial as running it locally.
[1] https://getfedora.org/en/workstation/prerelease/

**Comment by kparal** [comment]
I have [disabled extension version checking](http://worldofgnome.org/an-easy-way-to-test-extensions-compatibility-in-gnome-3-12/) in GNOME 3.18 and your extension seems to be working perfectly. So probably all you need is to update the metadata file and upload new version to extensions.gnome.org. If you could do that, that would be great.

**Comment by manno** [comment]
Thanks for testing on 3.18. I've uploaded a new version.
I'd very much welcome a new maintainer, however I'm unsure how this would be handled on https://extensions.gnome.org/

**Comment by kparal** [comment]
Thanks!

You can contact the admins and they'll transfer the ownership once someone like that is found, I believe. The call for new maintainer would be best visible directly in `README`, I think. Cheers.
